### ISSUE TITLE
How to use kanban template

### ISSUE THREAD

**Issue by oblab** [gristlabs/grist-pug-py-widget#1]
Hi @jperon i would like to use your kanban template for Grist but i don't understand how it work... Would you have time to explain me ? Also, i would love tu use it  as a supplement of the Lightweight CRM template : https://www.getgrist.com/templates/lightweight-crm-template/
thank you very much in advance !

**Comment by jperon** [comment]
Hello @oblab,
This widget allows you to define a custom widget directly in your document. So, to use it:

- create a custom widget with `Custom URL` pointing to `https://jperon.github.io/grist/Grist-pug-py-widget/` (or the url where you’d self-host it);
- upon creation, you’ll get a code editor with pug code, in which you’ll see a python script (instead of javascript, thanks to Brython);
- in the [Test](https://docs.getgrist.com/dd1Amj8bbHzK/Tests/p/20) document, click the `...` on top right of the kanban widget, then `Open configuration`;
- copy / paste the code, replacing the boilerplate you had in your own custom widget;
- `Preview`, then `Install`, then `Save`.

**Comment by oblab** [comment]
@jperon Merci, serait-il possible de vous contacter en message privé ? j'avais bien suivi le process que vous expliquez mais je n'obtiens rien en preview... Sans-doute une erreur dans ma configuration

**Comment by jperon** [comment]
Bien sûr : cataclop@hotmail.com
